### PR TITLE
Create Q1R1 - D

### PR DESCRIPTION
**Pull request by Wahaj404**
Test cases in original question are incomplete and flawed.

EDIT: Lines 26 and 32 should have 1000000000 not 10000.

### CODE REVIEW

**Comment by saadismail** [comment]
Thanks @Wahaj404 for the solution.

Though the logic seems right, it won't work on test cases as big as 10^9 because of limited allowed time (in the order of seconds). There has to be a way to optimize it even more than current O(n) solution.

**Comment by Wahaj404** [comment]
@saadismail What's O(n)?

**Comment by saadismail** [comment]
This is worst case notation, read more about here: https://en.wikipedia.org/wiki/Asymptotic_computational_complexity

It is impossible for a generic computer to process instructions of order 10^9 within few seconds so it will get TIME-LIMIT error.

**Comment by Wahaj404** [comment]
My program is going to 10^9 in ~45 seconds.
I tried loop unwinding (4 unwinds) but it only shaved off one second. How else can it be optimized?

**Pull request closed without merging**
